### ISSUE TITLE
Switch to express to serve status page

### ISSUE THREAD

**Issue by dittodhole** [dittodhole/node-upnp-scrobble-js#34]

**Comment by dittodhole** [comment]
When serving a request at '/', getting the followin error

<pre>
_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/pi/upnp-scrobble/upnp-scrobble/node_modules/express/lib/response.js:718:10)
    at ServerResponse.contentType (/home/pi/upnp-scrobble/upnp-scrobble/node_modules/express/lib/response.js:551:15)
    at ServerResponse.send (/home/pi/upnp-scrobble/upnp-scrobble/node_modules/express/lib/response.js:138:14)
    at done (/home/pi/upnp-scrobble/upnp-scrobble/node_modules/express/lib/response.js:957:10)
    at Immediate._onImmediate (/home/pi/upnp-scrobble/upnp-scrobble/node_modules/express-handlebars/lib/utils.js:26:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
</pre>
